### ISSUE TITLE
Minimum requirement for training

### ISSUE THREAD

**Issue by Extarys** [argosopentech/onmt-models#8]
I don't have a supercomputer but I wouldn't mind running a training model in the background for days, weeks or months, my electricity is cheap too.

Can I train on a "non server grade" computer?
What is the average amount of RAM/CPU required?
Can I train on an AMD graphic card (Vulkan)?.
Once trained, can I share/send it to Argos?

Thank you

**Comment by PJ-Finlay** [comment]
I'd definitely appreciate trained models!

You definitely need a GPU, Nvidia recommended but AMD is possible.

**Comment by PJ-Finlay** [comment]
- https://opennmt.net/OpenNMT-py/

**Comment by Extarys** [comment]
Thanks @PJ-Finlay !
Is there some languages that are either out of date from OPUS source or a pair that isn't trained yet but quite common? Or I just wing it?

**Comment by PJ-Finlay** [comment]
I would first just try to get it working with the default Spanish data in the Readme then whatever you want. There's a [language request form](https://github.com/argosopentech/argos-translate/discussions/91) with frequently requested languages. There's also lots of room to do direct (no pivot) translations between common non English language pairs like German-French.

**Comment by Extarys** [comment]
Sorry to bother again with this but I get errors of files missing. I have no idea what I'm doing by the way :P Just following what is written.
Here is what I did.

```
cd /mnt/libretranslate
git clone https://github.com/argosopentech/onmt-models.git
cd onmt-models
./setup.sh
PATH=$PATH:~/.local/bin/

# So far so good

cd ./raw_data
wget https://object.pouta.csc.fi/OPUS-Wikipedia/v1.0/moses/en-es.txt.zip
unzip en-es.txt.zip
cat raw_data/*.en >> source
cat raw_data/*.es >> target 

# Yup still ok

../argos-train

# Logs goes BRRR
```

Since argos-train is in `/mnt/libretranslate/onmt-models` with it's config.yml file, running it elsewhere throws an error, hence the `../`.

The output:
```
Preparing Data
mkdir: cannot create directory ‘run’: File exists
Read data from file
Done filtering data
Traceback (most recent call last):
  File "./prepare_data.py", line 50, in <module>
    os.mkdir('run/split_data')
NotADirectoryError: [Errno 20] Not a directory: 'run/split_data'
Training tokenizer
/home/user/.local/bin/argos-train: line 10: run/split_data/all.txt: Not a directory
sentencepiece_trainer.cc(77) LOG(INFO) Starts training with : 
trainer_spec {
  input: run/split_data/all.txt
  input_format: 
  model_prefix: sentencepiece
  model_type: UNIGRAM
  vocab_size: 8000
  self_test_sample_size: 0
  character_coverage: 0.9995
  input_sentence_size: 1000000
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars: 
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇ 
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv: 
}
denormalizer_spec {}
trainer_interface.cc(329) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(178) LOG(INFO) Loading corpus: run/split_data/all.txt
spm_train_main.cc(258) [_status.ok()] Not found: "run/split_data/all.txt": Not a directory Error #20
Program terminated with an unrecoverable error.
Traceback (most recent call last):
  File "/usr/local/bin/onmt_build_vocab", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py==2.1.2', 'console_scripts', 'onmt_build_vocab')())
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/bin/build_vocab.py", line 66, in main
    build_vocab_main(opts)
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/bin/build_vocab.py", line 23, in build_vocab_main
    ArgumentParser.validate_prepare_opts(opts, build_vocab_only=True)
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/utils/parse.py", line 159, in validate_prepare_opts
    cls._validate_data(opt)
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/utils/parse.py", line 55, in _validate_data
    cls._validate_file(path_src, info=f'{cname}/path_src')
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/utils/parse.py", line 18, in _validate_file
    raise IOError(f"Please check path of your {info} file!")
OSError: Please check path of your corpus_1/path_src file!
rm: cannot remove 'run/split_data/all.txt': Not a directory
Done with tokenization
Traceback (most recent call last):
  File "/usr/local/bin/onmt_train", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py==2.1.2', 'console_scripts', 'onmt_train')())
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/bin/train.py", line 172, in main
    train(opt)
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/bin/train.py", line 106, in train
    checkpoint, fields, transforms_cls = _init_train(opt)
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/bin/train.py", line 58, in _init_train
    ArgumentParser.validate_prepare_opts(opt)
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/utils/parse.py", line 159, in validate_prepare_opts
    cls._validate_data(opt)
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/utils/parse.py", line 55, in _validate_data
    cls._validate_file(path_src, info=f'{cname}/path_src')
  File "/usr/local/lib/python3.8/site-packages/OpenNMT_py-2.1.2-py3.8.egg/onmt/utils/parse.py", line 18, in _validate_file
    raise IOError(f"Please check path of your {info} file!")
OSError: Please check path of your corpus_1/path_src file!
```

From OpenMNT QuickStart guide, I should have 4 files:
```
src-train.txt
tgt-train.txt
src-val.txt
tgt-val.txt
```

My guess is that the purpose of `cat raw_data/*.en >> source` is to create `src-train` just with the wrong name, but even renaming those files the error persist, so I'm probably wrong. I also tried renaming `raw_data` to `split_data`, same issue.

Here is a quick screenshot of the folder structure to avoid misunderstanding:
![image](https://user-images.githubusercontent.com/11581433/132079214-25a94422-8a03-42a8-8091-5e67c2c2bb90.png)

I'm probably forgetting something quite stupid. Feel free to give me a hand when you have time or redirect me to a place where argos/libretranslate discussion stuff happens :smile: 

Sorry for the inconvenience. Thanks a lot.

**Comment by PJ-Finlay** [comment]
```
mkdir: cannot create directory ‘run’: File exists

```
All the training files are out in a `run` directory at runtime. `rm -rf run` to delete it.

**Comment by ecxod** [comment]
> 

> cd /mnt/libretranslate
> git clone https://github.com/argosopentech/onmt-models.git
> cd onmt-models
> ./setup.sh

there is no setup.sh in that folder. could you please advise?

**Comment by PJ-Finlay** [comment]
Are you using an older version?

I think you want:
```
source argos-train-init
```
